#  NumPy Array Functions

NumPy array functions are a set of built-in operations provided by the NumPy library that allow users to perform various tasks on arrays. With NumPy array functions, you can create, reshape, slice, sort, perform mathematical operations, and much more—all while taking advantage of the library's speed and efficiency.

In [1]:
import numpy as np

In [2]:
a = np.random.randint(10,50, size = (5,2,3))

In [3]:
a.dtype

dtype('int32')

In [4]:
a.shape

(5, 2, 3)

In [5]:
a.ndim

3

In [6]:
a.size

30

In [7]:
a.T

array([[[15, 47, 25, 28, 40],
        [29, 18, 16, 29, 37]],

       [[46, 46, 25, 27, 15],
        [29, 43, 35, 13, 17]],

       [[18, 42, 33, 16, 31],
        [13, 12, 29, 17, 12]]], dtype=int32)

In [9]:
np.transpose(a) # a.T is short form of it

array([[[15, 47, 25, 28, 40],
        [29, 18, 16, 29, 37]],

       [[46, 46, 25, 27, 15],
        [29, 43, 35, 13, 17]],

       [[18, 42, 33, 16, 31],
        [13, 12, 29, 17, 12]]], dtype=int32)

In [10]:
a = np.random.randint(10, 50, size = (5,4))

In [11]:
a

array([[47, 20, 27, 23],
       [36, 12, 12, 11],
       [47, 26, 42, 22],
       [23, 27, 31, 42],
       [41, 48, 35, 28]], dtype=int32)

In [16]:
a.reshape(4,5)

array([[47, 20, 27, 23, 36],
       [12, 12, 11, 47, 26],
       [42, 22, 23, 27, 31],
       [42, 41, 48, 35, 28]], dtype=int32)

In [17]:
a.reshape(10,2)

array([[47, 20],
       [27, 23],
       [36, 12],
       [12, 11],
       [47, 26],
       [42, 22],
       [23, 27],
       [31, 42],
       [41, 48],
       [35, 28]], dtype=int32)

In [18]:
a.reshape(2,10)

array([[47, 20, 27, 23, 36, 12, 12, 11, 47, 26],
       [42, 22, 23, 27, 31, 42, 41, 48, 35, 28]], dtype=int32)

In [19]:
a.reshape(3,4) # should be same elements while re-shaping

ValueError: cannot reshape array of size 20 into shape (3,4)

In [20]:
a.reshape(6,5) # should be same elements while re-shaping

ValueError: cannot reshape array of size 20 into shape (6,5)

In [21]:
a.reshape(-1, 2,5)

array([[[47, 20, 27, 23, 36],
        [12, 12, 11, 47, 26]],

       [[42, 22, 23, 27, 31],
        [42, 41, 48, 35, 28]]], dtype=int32)

In [22]:
a.reshape(2, 2,5)

array([[[47, 20, 27, 23, 36],
        [12, 12, 11, 47, 26]],

       [[42, 22, 23, 27, 31],
        [42, 41, 48, 35, 28]]], dtype=int32)

In [23]:
a.reshape(2,5,2)

array([[[47, 20],
        [27, 23],
        [36, 12],
        [12, 11],
        [47, 26]],

       [[42, 22],
        [23, 27],
        [31, 42],
        [41, 48],
        [35, 28]]], dtype=int32)

In [24]:
a.reshape(-1, 3)

ValueError: cannot reshape array of size 20 into shape (3)

In [25]:
a.reshape(-1, 4)

array([[47, 20, 27, 23],
       [36, 12, 12, 11],
       [47, 26, 42, 22],
       [23, 27, 31, 42],
       [41, 48, 35, 28]], dtype=int32)

In [27]:
b = a.flatten() # a.ravel()
b

array([47, 20, 27, 23, 36, 12, 12, 11, 47, 26, 42, 22, 23, 27, 31, 42, 41,
       48, 35, 28], dtype=int32)

In [32]:
a

array([[47, 20, 27, 23],
       [36, 12, 12, 11],
       [47, 26, 42, 22],
       [23, 27, 31, 42],
       [41, 48, 35, 28]], dtype=int32)

In [28]:
a.sum()

np.int64(600)

In [38]:
a.sum(axis = 0) # exis = 0 is row wise sum or horizental sum

array([194, 133, 147, 126])

In [37]:
a.sum(axis = 1) #exis = 1 is column wise sum or vertical sum

array([117,  71, 137, 123, 152])

In [39]:
a.trace() # diagonal sum

np.int64(143)

In [40]:
np.cumsum(a, axis = 0)

array([[ 47,  20,  27,  23],
       [ 83,  32,  39,  34],
       [130,  58,  81,  56],
       [153,  85, 112,  98],
       [194, 133, 147, 126]])

In [42]:
np.cumsum(a, axis = 1)

array([[ 47,  67,  94, 117],
       [ 36,  48,  60,  71],
       [ 47,  73, 115, 137],
       [ 23,  50,  81, 123],
       [ 41,  89, 124, 152]])

In [43]:
np.prod(a)

np.int64(8075265714199724032)

In [44]:
np.prod(a, axis = 1)

array([ 583740,   57024, 1129128,  808542, 1928640])

In [46]:
np.prod(np.cumsum(a, axis=1))

np.int64(-3178151660023414784)

In [47]:
np.max(a)

np.int32(48)

In [48]:
np.mean(a)

np.float64(30.0)

In [49]:
np.median(a)

np.float64(27.5)

In [51]:
a

array([[47, 20, 27, 23],
       [36, 12, 12, 11],
       [47, 26, 42, 22],
       [23, 27, 31, 42],
       [41, 48, 35, 28]], dtype=int32)

In [50]:
np.argmax(a, axis = 1)

array([0, 0, 0, 3, 1])

In [52]:
 np.argmax(a, axis = 0)

array([0, 4, 2, 3])

In [53]:
np.argmin(a, axis = 0)

array([3, 1, 1, 1])

In [54]:
np.argmin(a, axis = 1)

array([1, 3, 3, 0, 3])

In [55]:
np.clip(a, 20, 30)

array([[30, 20, 27, 23],
       [30, 20, 20, 20],
       [30, 26, 30, 22],
       [23, 27, 30, 30],
       [30, 30, 30, 28]], dtype=int32)

In [63]:
arr1 = np.random.randint(1,100, size = (3,3))
arr2 = np.random.randint(1,100, size = (5,3))

In [65]:
arr1

array([[35, 81, 81],
       [22, 55, 41],
       [59,  4, 69]], dtype=int32)

In [66]:
arr2

array([[34, 85, 66],
       [82, 69, 23],
       [46, 55, 73],
       [17, 54,  2],
       [60, 89, 77]], dtype=int32)

In [67]:
d = np.concatenate([arr1,arr2], axis=0)

In [68]:
d

array([[35, 81, 81],
       [22, 55, 41],
       [59,  4, 69],
       [34, 85, 66],
       [82, 69, 23],
       [46, 55, 73],
       [17, 54,  2],
       [60, 89, 77]], dtype=int32)

In [73]:
d = np.concatenate([arr1,arr2], axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 5

In [76]:
np.vstack

<function vstack at 0x000001A6E37495B0>

In [77]:
np.vstack([arr1,arr2])

array([[35, 81, 81],
       [22, 55, 41],
       [59,  4, 69],
       [34, 85, 66],
       [82, 69, 23],
       [46, 55, 73],
       [17, 54,  2],
       [60, 89, 77]], dtype=int32)

In [78]:
np.hstack([arr1,arr2])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 5

In [80]:
np.split(d, 3, axis = 1)

[array([[35],
        [22],
        [59],
        [34],
        [82],
        [46],
        [17],
        [60]], dtype=int32),
 array([[81],
        [55],
        [ 4],
        [85],
        [69],
        [55],
        [54],
        [89]], dtype=int32),
 array([[81],
        [41],
        [69],
        [66],
        [23],
        [73],
        [ 2],
        [77]], dtype=int32)]

In [82]:
np.split(d, 2, axis = 0)

[array([[35, 81, 81],
        [22, 55, 41],
        [59,  4, 69],
        [34, 85, 66]], dtype=int32),
 array([[82, 69, 23],
        [46, 55, 73],
        [17, 54,  2],
        [60, 89, 77]], dtype=int32)]