In [1]:
import numpy as np

In [3]:
a = np.array([[4,5,6], [1,2,4]])
b = np.array([[8,6,0], [3,2,4]])

In [4]:
a, b

(array([[4, 5, 6],
        [1, 2, 4]]),
 array([[8, 6, 0],
        [3, 2, 4]]))

In [6]:
a + b # can also use function np.add(a,b)


array([[12, 11,  6],
       [ 4,  4,  8]])

In [7]:
np.subtract(a,b)  # also use a-b

array([[-4, -1,  6],
       [-2,  0,  0]])

In [10]:
# a**2
np.pow(a, 2)

array([[16, 25, 36],
       [ 1,  4, 16]])

In [14]:
# a % b

quo, rem = np.divmod(a,b)
quo

C:\Users\Suresh\AppData\Local\Temp\ipykernel_22992\3604446247.py:3: RuntimeWarning: divide by zero encountered in divmod
  quo, rem = np.divmod(a,b)


array([[0, 0, 0],
       [0, 1, 1]])

In [11]:
c = np.array([[8,4,0], [3,11,4]]) # adding 3rd array

## Trignometric

In [15]:
np.sin(a)

array([[-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.84147098,  0.90929743, -0.7568025 ]])

In [18]:
cot = 1/np.tan(a)
cot

array([[ 0.86369115, -0.29581292, -3.436353  ],
       [ 0.64209262, -0.45765755,  0.86369115]])

In [17]:
np.cos(a)

array([[-0.65364362,  0.28366219,  0.96017029],
       [ 0.54030231, -0.41614684, -0.65364362]])

## Rounding Operations

In [19]:
np.around(cot, 2)

array([[ 0.86, -0.3 , -3.44],
       [ 0.64, -0.46,  0.86]])

In [20]:
np.fix(cot)

array([[ 0., -0., -3.],
       [ 0., -0.,  0.]])

In [23]:
np.floor(cot)

array([[ 0., -1., -4.],
       [ 0., -1.,  0.]])

In [24]:
np.ceil(cot)

array([[ 1., -0., -3.],
       [ 1., -0.,  1.]])

## 2. Matrix Operations 

In [25]:
a,b

(array([[4, 5, 6],
        [1, 2, 4]]),
 array([[8, 6, 0],
        [3, 2, 4]]))

In [26]:
a*b

array([[32, 30,  0],
       [ 3,  4, 16]])

In [27]:
a @ b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [28]:
b = np.random.randint(0,10, (3,4))

In [29]:
b

array([[8, 9, 2, 3],
       [9, 9, 1, 6],
       [9, 7, 0, 2]], dtype=int32)

In [32]:
a

array([[4, 5, 6],
       [1, 2, 4]])

In [30]:
res = np.dot(a,b)

In [31]:
res


array([[131, 123,  13,  54],
       [ 62,  55,   4,  23]])

In [33]:
a @ b

array([[131, 123,  13,  54],
       [ 62,  55,   4,  23]])

In [35]:
a.T

array([[4, 1],
       [5, 2],
       [6, 4]])

In [36]:
np.transpose(a)

array([[4, 1],
       [5, 2],
       [6, 4]])

In [37]:
np.trace(b)

np.int64(17)

In [38]:
#Inverse of an matrix or array

a_det = np.linalg.det(a)

LinAlgError: Last 2 dimensions of the array must be square

In [41]:
sq = np.random.randint(0,10, (3,3))
a_det = np.linalg.det(sq)

In [42]:
inv_sq = np.linalg.inv(sq)

In [45]:
np.dot(sq,inv_sq)

array([[ 1.00000000e+00,  0.00000000e+00, -2.22044605e-16],
       [-5.55111512e-17,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [46]:
np.dot(sq,inv_sq).round()

array([[ 1.,  0., -0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])

solve equation : `4x + 2y = 8` , `5x = 3y = 9`

In [49]:
a = np.array(
    [
        [4,2],
        [5,3]
    ]
)

b = np.array([8,9])

In [53]:
a_inv = np.array(a)

In [54]:
np.dot(a_inv,b)

array([50, 67])

In [57]:
## Array Broadcasting 

In [58]:
a * b

array([[32, 18],
       [40, 27]])