In [1]:
!pip install tensorflow


In [2]:
import tensorflow as tf



In [3]:
tf.__version__

'2.20.0'

In [4]:
import pandas as pd

data = pd.read_csv("Iris.csv", index_col=0)
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [6]:
X = data.drop("Species", axis=1).to_numpy()
y = data[["Species"]].to_numpy()

In [7]:
scaler = StandardScaler()
onehot_encoder = OneHotEncoder(sparse_output=False)

enc_y = onehot_encoder.fit_transform(y)
scaled_X = scaler.fit_transform(X)

In [8]:
cat_array = onehot_encoder.categories_[0]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    scaled_X, enc_y, test_size=0.2, shuffle=True, stratify=enc_y, random_state=999
)

In [10]:
X_train.shape

(120, 4)

In [11]:
y_train.shape

(120, 3)

# Model Creation and Compile 

In [12]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense

In [13]:
inp_shape = X_train.shape[1]
num_clases = y_train.shape[1]

In [14]:
model = Sequential()

model.add(Input(shape= (inp_shape,)))

model.add(Dense(64, activation="relu"))
model.add(Dense(32, activation="relu"))

model.add(Dense(num_clases, activation="softmax"))

In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,499 (9.76 KB)

 Trainable params: 2,499 (9.76 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.compile(
    optimizer="Adam", loss="categorical_crossentropy", metrics=["accuracy", "f1_score"]
)

In [17]:
history = model.fit(
    X_train, y_train, epochs=25, batch_size=32, verbose=1
)

Epoch 1/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.5833 - f1_score: 0.4699 - loss: 0.9912
Epoch 2/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6417 - f1_score: 0.5140 - loss: 0.9173
Epoch 3/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6500 - f1_score: 0.5199 - loss: 0.8498
Epoch 4/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6833 - f1_score: 0.5826 - loss: 0.7897
Epoch 5/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7667 - f1_score: 0.7310 - loss: 0.7316
Epoch 6/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7833 - f1_score: 0.7611 - loss: 0.6826
Epoch 7/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7917 - f1_score: 0.7732 - loss: 0.6364
Epoch 8/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8083 - f1_score: 0.7954 - loss: 0.5943
Epoch 9/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8083 - f1_score: 0.7954 - loss: 0.5555
Epoch 10/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8167 - f1_score: 0

In [18]:
history.history

{'accuracy': [0.5833333134651184,
  0.6416666507720947,
  0.6499999761581421,
  0.6833333373069763,
  0.7666666507720947,
  0.7833333611488342,
  0.7916666865348816,
  0.8083333373069763,
  0.8083333373069763,
  0.8166666626930237,
  0.8333333134651184,
  0.8333333134651184,
  0.8416666388511658,
  0.8416666388511658,
  0.8416666388511658,
  0.8416666388511658,
  0.8416666388511658,
  0.8416666388511658,
  0.8500000238418579,
  0.875,
  0.875,
  0.875,
  0.8916666507720947,
  0.9166666865348816,
  0.9166666865348816],
 'f1_score': [array([0.6779661, 0.       , 0.7317072], dtype=float32),
  array([0.75471693, 0.        , 0.78723407], dtype=float32),
  array([0.7843137 , 0.        , 0.77551013], dtype=float32),
  array([0.8510637 , 0.13953486, 0.75728154], dtype=float32),
  array([0.93023247, 0.49056596, 0.7722772 ], dtype=float32),
  array([0.9638554, 0.5517241, 0.7676768], dtype=float32),
  array([0.9756097, 0.5762711, 0.7676768], dtype=float32),
  array([0.98765427, 0.6229508 , 0.7755

In [19]:
model.evaluate(X_test, y_test)



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 339ms/step - accuracy: 0.9333 - f1_score: 0.9327 - loss: 0.2602


[0.26019802689552307,
 0.9333333373069763,
 array([1.       , 0.8888889, 0.9090909], dtype=float32)]

In [20]:
y_pred = np.argmax(model.predict(X_test), axis=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step


In [21]:
y_true = np.argmax(y_test, axis=1)

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score

In [23]:
confusion_matrix(y_true, y_pred)

array([[10,  0,  0],
       [ 0,  8,  2],
       [ 0,  0, 10]])

In [24]:
accuracy_score(y_true, y_pred)

0.9333333333333333

In [25]:
f1_score(y_true, y_pred, average="macro")

0.9326599326599326

In [26]:
precision_score(y_true, y_pred, average="macro")

0.9444444444444445

In [27]:
recall_score(y_true, y_pred, average="macro")

0.9333333333333332

# Packaging a Model

In [30]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,499 (29.30 KB)

 Trainable params: 2,499 (9.76 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 5,000 (19.54 KB)

In [28]:
model.save("iris_classification.keras")

In [29]:
import pickle

In [31]:
to_package = {
    "scaler": scaler,
    "encoder": onehot_encoder,
    "model": model
}

with open("iris_classifier.pkl", "wb") as file: 
    pickle.dump(to_package, file)