Numpy - Slicing 

In [4]:
import numpy as np

In [5]:
a = np.array([1, 2, 3, 4, 5, 6,])

In [6]:
print(a[-3])

4


In [7]:
a[2::1]

array([3, 4, 5, 6])

In [15]:
#2D

arr = np.random.randint(0, 10, size = (5, 4))
arr


array([[9, 0, 2, 5],
       [7, 8, 4, 4],
       [1, 0, 1, 9],
       [6, 7, 1, 7],
       [9, 0, 7, 6]], dtype=int32)

In [9]:
arr[1, 0] #or arr [1][0]

np.int32(9)

In [10]:
arr [-1, -1]

np.int32(8)

In [13]:
#slicing 2D array : (aray[<row_slice>, <col_slice>])
arr[1:3, 0:3]

array([[9, 1, 8]], dtype=int32)

In [16]:
arr[:2,3]

array([5, 4], dtype=int32)

In [17]:
#3D
arr = np.random.randint(0, 10, size = (3,4,3))
arr

array([[[3, 0, 8],
        [7, 1, 5],
        [7, 6, 0],
        [8, 8, 6]],

       [[1, 8, 4],
        [0, 3, 5],
        [0, 1, 3],
        [7, 2, 7]],

       [[5, 6, 4],
        [8, 3, 0],
        [5, 6, 6],
        [5, 3, 3]]], dtype=int32)

In [18]:
arr[1, -1, 2]

np.int32(7)

In [22]:
arr[0]


array([[3, 0, 8],
       [7, 1, 5],
       [7, 6, 0],
       [8, 8, 6]], dtype=int32)

In [23]:
arr[1]

array([[1, 8, 4],
       [0, 3, 5],
       [0, 1, 3],
       [7, 2, 7]], dtype=int32)

In [24]:
arr[2]

array([[5, 6, 4],
       [8, 3, 0],
       [5, 6, 6],
       [5, 3, 3]], dtype=int32)

In [26]:
arr[:,:2,:]

array([[[3, 0, 8],
        [7, 1, 5]],

       [[1, 8, 4],
        [0, 3, 5]],

       [[5, 6, 4],
        [8, 3, 0]]], dtype=int32)

In [27]:
dataset = np.random.randint(0,255, (16,3,720,724))

In [28]:
dataset

array([[[[181, 196, 221, ...,   9, 245,  11],
         [193,  65, 242, ..., 129, 100, 149],
         [204, 144, 205, ...,  68, 132,  35],
         ...,
         [210, 178, 247, ..., 179, 173,   7],
         [ 45, 253, 101, ..., 227, 201,  13],
         [  8, 157, 118, ...,  14, 166, 215]],

        [[ 75, 152,  67, ...,  66, 226,   6],
         [184,  39, 229, ..., 239,  60,  78],
         [ 68, 172,  58, ..., 236, 149,  72],
         ...,
         [ 34, 102,  25, ..., 211, 240,  96],
         [168,  34,  82, ..., 240, 170, 125],
         [ 41, 221,  11, ...,  73, 200,  63]],

        [[ 34, 133,  94, ..., 232, 178, 244],
         [ 46,  35, 151, ..., 213,  20, 174],
         [ 27,  14, 182, ...,  79, 108, 216],
         ...,
         [210,  59, 192, ...,  27, 189, 116],
         [ 53,   9, 164, ...,   3,  24, 217],
         [133, 243, 164, ..., 200,  49, 122]]],


       [[[143, 230, 211, ..., 104,  45, 141],
         [249, 191, 140, ...,  13, 156,   0],
         [ 86, 192,  12, ..., 

In [29]:
dataset.shape


(16, 3, 720, 724)

In [30]:
!pip install %matplotlib


ERROR: Invalid requirement: '%matplotlib': Expected package name at the start of dependency specifier
    %matplotlib
    ^


In [31]:
import matplotlib_inline

ModuleNotFoundError: No module named 'matplotlib'

In [32]:
plt.imshow(dataset)

NameError: name 'plt' is not defined