# Math
### LinearAlgebra
To learn linear algebra for data science using Python, consider the following resources: Coursera Specialization: Offers a structured course covering linear algebra concepts and their applications in data science, including programming assignments and a capstone project. 1 Books: "Linear Algebra for Data Science with Python" provides an introduction to vectors, matrices, and their applications in data science. 1 "Practical Linear Algebra for Data Science" teaches core concepts of linear algebra as implemented in Python, focusing on modern applications in data science and machine learning. 1 GitHub Repository: Contains Jupyter notebooks demonstrating key linear algebra concepts applied to data science and machine learning, focusing on practical implementations using Python libraries. 1 Additional Resources: Explore various courses and projects that integrate linear algebra with data science, enhancing your understanding and practical skills. 1

These resources will help you grasp the essential concepts of linear algebra and their relevance in data science.

# Numpy

In [5]:
!pip install numpy

In [6]:
import numpy as np

In [7]:
np.__version__

'2.4.0'

 ### Creating Numpy array

In [8]:
list1 = [2,3,4]

In [9]:
arr1 = np.array(list1)

In [10]:
arr1

array([2, 3, 4])

In [11]:
arr1.shape

(3,)

In [12]:
arr1.ndim

1

In [17]:
list1 = [[2,3,4], [6,7,8], [6,8,0]]
arr1 = np.array(list1)

In [19]:
arr1

array([[2, 3, 4],
       [6, 7, 8],
       [6, 8, 0]])

In [21]:
arr1.shape

(3, 3)

In [22]:
arr1.ndim

2

In [23]:
list1 = [[2,3,4], [6,7,8], [6,8,0]], [[2,3,4], [6,7,8], [6,8,0]]
arr1 = np.array(list1)

In [24]:
arr1

array([[[2, 3, 4],
        [6, 7, 8],
        [6, 8, 0]],

       [[2, 3, 4],
        [6, 7, 8],
        [6, 8, 0]]])

In [26]:
arr1.shape

(2, 3, 3)

In [27]:
arr1.ndim

3

#### NumPy arrays can be created in several ways. Here are some of the most common mehods: 

array :
zeros:
ones:
full :
arange:
linspace:
diag:
eye:
identity:
random.rand.

In [28]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [29]:
np.zeros((2, 2,3), dtype=int)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [30]:
np.zeros((4, 2,3), dtype=int)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

A small  100X100 pixal picture, may have below array

In [31]:
np.zeros((3, 100, 100), dtype=int)

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]], shape=(3, 100, 100))

In [32]:
np.full((3,4), fill_value=6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [34]:
np.arange(1,90,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86])

In [35]:
np.arange(0,90,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85])

In [37]:
np.linspace(0,30, num = 13)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5, 30. ])

In [41]:
arr2 = np.linspace((0,1,2), (10,20,30), num = 5)
arr2

array([[ 0.  ,  1.  ,  2.  ],
       [ 2.5 ,  5.75,  9.  ],
       [ 5.  , 10.5 , 16.  ],
       [ 7.5 , 15.25, 23.  ],
       [10.  , 20.  , 30.  ]])

In [42]:
arr2.shape

(5, 3)

In [43]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.random

<module 'numpy.random' from 'C:\\Users\\Suresh\\Desktop\\DSML\\Projects\\DS-P1\\.venv\\Lib\\site-packages\\numpy\\random\\__init__.py'>

In [45]:
np.random.randint(0,10, size = (2,2))

array([[5, 4],
       [0, 7]], dtype=int32)

In [46]:
np.random.randint(0,10, size = (2,3))

array([[0, 8, 6],
       [2, 8, 2]], dtype=int32)

In [49]:
np.random.randint(0,50, size = (4,2,3))

array([[[42, 10, 46],
        [ 8, 16, 10]],

       [[34, 39, 23],
        [ 3, 35, 31]],

       [[16, 25, 29],
        [38, 46, 31]],

       [[33, 30, 27],
        [39, 47,  9]]], dtype=int32)