### **Assignment: Introduction to Linear Algebra and NumPy**

#### **Objective:**
This assignment will help you build a solid understanding of basic Linear Algebra concepts using Python and the NumPy library. You'll learn to create and manipulate arrays, perform mathematical operations, and explore properties and methods of arrays.


### **Working with NumPy**

NumPy is a powerful Python library for numerical computations, which allows easy manipulation of arrays and matrices.

**Task 1:** 
- Import the `numpy` library and check its version.


In [7]:
# Solution Here

import numpy as np




In [11]:
np.__version__

'2.4.0'


### **Creating a NumPy Array:**

NumPy arrays are a powerful way to store and process large datasets. In this section, you will learn to create arrays.

**Task 2:**
- Create a 1D NumPy array from a Python list of numbers: `[1, 2, 3, 4, 5]`.
- Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
- Generate an array of 10 evenly spaced values between 0 and 5.

In [19]:
# Solution Here

#Create a 1D NumPy array from a Python list of numbers: [1, 2, 3, 4, 5].
arr_1d = np.array([1, 2, 3, 4, 5])
arr_1d

array([1, 2, 3, 4, 5])

In [32]:
# Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.

arr_2d = np.random.randint(1, 9, size = (2,3,3))
arr_2d

array([[[6, 6, 6],
        [1, 8, 5],
        [5, 6, 4]],

       [[1, 3, 6],
        [6, 8, 8],
        [5, 7, 7]]], dtype=int32)

In [16]:
# Generate an array of 10 evenly spaced values between 0 and 5.

arr_linspace = np.linspace(0, 5, 10)
arr_linspace

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### **Indexing and Slicing Arrays:**

Indexing and slicing allow you to access and modify specific elements of an array.

**Task 3:**
- Access the element in the second row, third column of the 2D array you created above.
- Slice the first two rows and the first two columns from the same array.
- Modify the value in the last row and first column to 100.


In [33]:
# Solution Here
#the element in the second row, third column of the 2D array you created above.

arr_2d

array([[[6, 6, 6],
        [1, 8, 5],
        [5, 6, 4]],

       [[1, 3, 6],
        [6, 8, 8],
        [5, 7, 7]]], dtype=int32)

In [35]:
element = arr_2d[0,1,2]
element

np.int32(5)

In [47]:
arr_2d[1,1,2]

np.int32(8)

In [46]:
# Slice the first two rows and the first two columns from the same array.
arr_2d[0:2,0:2, 0:2]

array([[[6, 6],
        [1, 8]],

       [[1, 3],
        [6, 8]]], dtype=int32)

In [49]:
# Modify the value in the last row and first column to 100.

arr_2d[1,2,0] = 100

arr_2d

array([[[  6,   6,   6],
        [  1,   8,   5],
        [  5,   6,   4]],

       [[  1,   3,   6],
        [  6,   8,   8],
        [100,   7,   7]]], dtype=int32)

In [50]:
arr_2d[0,2,0] = 100

arr_2d

array([[[  6,   6,   6],
        [  1,   8,   5],
        [100,   6,   4]],

       [[  1,   3,   6],
        [  6,   8,   8],
        [100,   7,   7]]], dtype=int32)

### **Properties and Methods of NumPy Arrays**

NumPy arrays have several useful properties and methods.

**Task 4:**
- Find the shape, size, and data type of the 2D array.
- Change the 1D array into a 2D array of shape (5,1).
- Flatten a multi-dimensional array back into a 1D array.

In [56]:
# Solution Here

#Find the shape, size, and data type of the 2D array.

In [54]:
arr_2d.shape


(2, 3, 3)

In [52]:
arr_2d.size

18

In [53]:
arr_2d.dtype

dtype('int32')

In [64]:
# Change the 1D array into a 2D array of shape (5,1).

arr_1d

array([1, 2, 3, 4, 5])

In [65]:
arr_1d.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [67]:
# Flatten a multi-dimensional array back into a 1D array.
arr_2d.flatten()

array([  6,   6,   6,   1,   8,   5, 100,   6,   4,   1,   3,   6,   6,
         8,   8, 100,   7,   7], dtype=int32)

In [68]:
arr_1d.flatten()

array([1, 2, 3, 4, 5])

### **Operations on NumPy Arrays**

Perform operations such as addition, subtraction, multiplication, and matrix multiplication on arrays.

**Task 5:**
- Add 5 to every element in the 1D array.
- Multiply the 2D array by 3.
- Perform matrix multiplication between the following two arrays:  
    ```python
    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])

In [69]:
# Solution Here

#Add 5 to every element in the 1D array.

arr_1d + 5

array([ 6,  7,  8,  9, 10])

In [70]:
# Multiply the 2D array by 3.

arr_2d * 3

array([[[ 18,  18,  18],
        [  3,  24,  15],
        [300,  18,  12]],

       [[  3,   9,  18],
        [ 18,  24,  24],
        [300,  21,  21]]], dtype=int32)

In [74]:
# Perform matrix multiplication between the following two arrays: ```python A = np.array([[1, 2], [3, 4]]) B = np.array([[5, 6], [7, 8]])

A = np.array([[1, 2],
              [3, 4]]) 
B = np.array([[5, 6],
              [7, 8]])

In [80]:
A, B

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [81]:
A @ B

array([[19, 22],
       [43, 50]])

In [82]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

### **Understanding Broadcasting**

Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations.

**Task 6:**
- Create a 3x3 matrix of ones and a 1D array of length 3.
- Add the 1D array to each row of the matrix using broadcasting.

In [88]:
# Solution Here

matrix = np.ones((3,3))
matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [101]:
arr_1d = np.array([1, 2, 3])
print(arr_1d)


[1 2 3]


In [102]:
result = matrix + arr_1d

In [103]:
result


array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])