In [10]:
import pandas as pd

cleaned_titanic_df = pd.read_csv("Cleaned_Titanic.csv")

In [11]:
cleaned_titanic_df.head()

Unnamed: 0  PassengerId new_initial  Survived  Pclass  \
0           0          1.0          Mr       0.0     3.0   
1           1          2.0         Mrs       1.0     1.0   
2           2          3.0        Miss       1.0     3.0   
3           3          4.0         Mrs       1.0     1.0   
4           4          5.0          Mr       0.0     3.0   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0    1.0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0    1.0   
2                             Heikkinen, Miss. Laina  female  26.0    0.0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0    1.0   
4                           Allen, Mr. William Henry    male  35.0    0.0   

   Parch            Ticket     Fare Cabin Embarked initials  
0    0.0         A/5 21171   7.2500   NaN        S       Mr  
1    0.0          PC 17599  71.2833   C85        C      Mrs  
2    0.0  STON/O2. 3101282   7.9250   NaN        S     Miss  
3    0.0            113803  53.1000  C123        S      Mrs  
4    0.0            373450   8.0500   NaN        S       Mr

In [12]:
cleaned_titanic_df = cleaned_titanic_df.drop(
    columns=["Age", "Name", "Ticket", "SibSp", "Pclass"]
)

In [13]:
cleaned_titanic_df = cleaned_titanic_df.drop(
    columns=["Unnamed: 0", "initials", "new_initial"]
)


In [14]:
cleaned_titanic_df.head()

PassengerId  Survived     Sex  Parch     Fare Cabin Embarked
0          1.0       0.0    male    0.0   7.2500   NaN        S
1          2.0       1.0  female    0.0  71.2833   C85        C
2          3.0       1.0  female    0.0   7.9250   NaN        S
3          4.0       1.0  female    0.0  53.1000  C123        S
4          5.0       0.0    male    0.0   8.0500   NaN        S

Label Encoding

In [6]:
!pip install scikit-learn

   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.0 MB 887.8 kB/s eta 0:00:09
   -- ------------------------------------- 0.5/8.0 MB 887.8 kB/s eta 0:00:09
   --- ------------------------------------ 0.8/8.0 MB 801.4 kB/s eta 0:00:09
   --- ------------------------------------ 0.8/8.0 MB 801.4 kB/s eta 0:00:09
   ----- ---------------------------------- 1.0/8.0 MB 663.5 kB/s eta 0:00:11
   ----- ---------------------------------- 1.0/8.0 MB 663.5 kB/s eta 0:00:11
   ----- ---------------------------------- 1.0/8.0 MB 663.5 kB/s eta 0:00:11
   ------ --------------------------------- 1.3/8.0 MB 553.0 kB/s eta 0:00:13
   ------ --------------------------------- 1.3/8.0 MB 553.0 kB/s eta 0:00:13
   ------ ------------

In [7]:
from sklearn.preprocessing import OneHotEncoder

In [8]:
one_hot_encoder = OneHotEncoder(sparse_output=False)

In [9]:
one_hot_encoder

OneHotEncoder(sparse_output=False)

In [53]:
encoder_gender = one_hot_encoder.fit_transform(cleaned_titanic_df[["Sex"]])

In [11]:
encoder_gender

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [0., 1.]], shape=(889, 2))

In [54]:
cleaned_titanic_df["Sex"]

0        male
1      female
2      female
3      female
4        male
        ...  
884      male
885    female
886    female
887      male
888      male
Name: Sex, Length: 889, dtype: object

In [55]:
one_hot_encoder.categories_

[array(['female', 'male'], dtype=object)]

In [56]:
one_hot_encoder.inverse_transform(
    [[1,0],
     [0,1]]
)

array([['female'],
       ['male']], dtype=object)

In [17]:
one_hot_encoder.inverse_transform(
    encoder_gender
)

array([['male'],
       ['female'],
       ['female'],
       ['female'],
       ['male'],
       ['male'],
       ['male'],
       ['male'],
       ['female'],
       ['female'],
       ['female'],
       ['female'],
       ['male'],
       ['male'],
       ['female'],
       ['female'],
       ['male'],
       ['male'],
       ['female'],
       ['female'],
       ['male'],
       ['male'],
       ['female'],
       ['male'],
       ['female'],
       ['female'],
       ['male'],
       ['male'],
       ['female'],
       ['male'],
       ['male'],
       ['female'],
       ['female'],
       ['male'],
       ['male'],
       ['male'],
       ['male'],
       ['male'],
       ['female'],
       ['female'],
       ['female'],
       ['female'],
       ['male'],
       ['female'],
       ['female'],
       ['male'],
       ['male'],
       ['female'],
       ['male'],
       ['female'],
       ['male'],
       ['male'],
       ['female'],
       ['female'],
       ['male'],
       ['ma

In [57]:
df = pd.DataFrame(encoder_gender, columns=one_hot_encoder.categories_[0])

In [58]:
cleaned_titanic_df = pd.concat([cleaned_titanic_df, df], axis = 1)
cleaned_titanic_df

PassengerId  Survived     Sex  Parch Cabin Embarked  female  male  \
0            1.0       0.0    male    0.0   NaN        S     0.0   1.0   
1            2.0       1.0  female    0.0   C85        C     1.0   0.0   
2            3.0       1.0  female    0.0   NaN        S     1.0   0.0   
3            4.0       1.0  female    0.0  C123        S     1.0   0.0   
4            5.0       0.0    male    0.0   NaN        S     0.0   1.0   
..           ...       ...     ...    ...   ...      ...     ...   ...   
884        887.0       0.0    male    0.0   NaN        S     0.0   1.0   
885        888.0       1.0  female    0.0   B42        S     1.0   0.0   
886        889.0       0.0  female    2.0   NaN        S     1.0   0.0   
887        890.0       1.0    male    0.0  C148        C     0.0   1.0   
888        891.0       0.0    male    0.0   NaN        Q     0.0   1.0   

     Embarked_encoded  female  male  
0                   2     0.0   1.0  
1                   0     1.0   0.0  
2                   2     1.0   0.0  
3                   2     1.0   0.0  
4                   2     0.0   1.0  
..                ...     ...   ...  
884                 2     0.0   1.0  
885                 2     1.0   0.0  
886                 2     1.0   0.0  
887                 0     0.0   1.0  
888                 1     0.0   1.0  

[889 rows x 11 columns]

In [59]:
encoder_data = one_hot_encoder.fit_transform(cleaned_titanic_df[["Sex", "Embarked"]])

In [60]:
encoder_data

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]], shape=(889, 5))

In [61]:
one_hot_encoder.categories_

[array(['female', 'male'], dtype=object), array(['C', 'Q', 'S'], dtype=object)]

In [62]:
import numpy as np

np.hstack(
    cleaned_titanic_df.drop(["Sex", "Embarked"], axis =1).values, encoder_data
)[0]

TypeError: hstack() takes 1 positional argument but 2 were given

## Ordinal Data

data with order

In [63]:
cleaned_titanic_df.Embarked

0      S
1      C
2      S
3      S
4      S
      ..
884    S
885    S
886    S
887    C
888    Q
Name: Embarked, Length: 889, dtype: object

In [64]:
op_df, rule = cleaned_titanic_df.Embarked.factorize()

In [65]:
rule

Index(['S', 'C', 'Q'], dtype='object')

In [35]:
op_df

array([0, 1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0,
       2, 0, 0, 0, 1, 0, 2, 0, 1, 1, 2, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       2, 0, 2, 2, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0,
       1, 0, 0, 1, 0, 2, 0, 1, 0, 0, 0, 1, 0, 0, 1, 2, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 1, 1, 2, 0, 2,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 1, 0, 0, 0, 0, 2, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0,
       0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 2, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 1, 0,
       0, 0, 2, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 2, 2,

In [68]:
cleaned_titanic_df["Embarked_encoded"], rule = cleaned_titanic_df.Embarked.factorize(sort = True)

In [66]:
cleaned_titanic_df.head()

PassengerId  Survived     Sex  Parch Cabin Embarked  female  male  \
0          1.0       0.0    male    0.0   NaN        S     0.0   1.0   
1          2.0       1.0  female    0.0   C85        C     1.0   0.0   
2          3.0       1.0  female    0.0   NaN        S     1.0   0.0   
3          4.0       1.0  female    0.0  C123        S     1.0   0.0   
4          5.0       0.0    male    0.0   NaN        S     0.0   1.0   

   Embarked_encoded  female  male  
0                 2     0.0   1.0  
1                 0     1.0   0.0  
2                 2     1.0   0.0  
3                 2     1.0   0.0  
4                 2     0.0   1.0

In [69]:
#SKlearn

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
encoded_e = label_encoder.fit_transform(cleaned_titanic_df["Embarked"])


In [43]:
encoded_e

array([2, 0, 2, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2,
       1, 2, 2, 2, 0, 2, 1, 2, 0, 0, 1, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0,
       1, 2, 1, 1, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2,
       0, 2, 2, 0, 2, 1, 2, 0, 2, 2, 2, 0, 2, 2, 0, 1, 2, 0, 2, 0, 2, 2,
       2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2,
       0, 2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 0, 0, 1, 2, 1,
       2, 2, 2, 2, 0, 2, 2, 2, 0, 1, 0, 2, 2, 2, 2, 1, 0, 2, 2, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 2,
       2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 0, 2,
       2, 2, 1, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 1, 1,

In [44]:
label_encoder.classes_

array(['C', 'Q', 'S'], dtype=object)

In [45]:
label_encoder.inverse_transform(
    [1,2,0,1,2]
)

array(['Q', 'S', 'C', 'Q', 'S'], dtype=object)

In [70]:
label_encoder.inverse_transform(
    [1,2,0,1,2,3]
)

ValueError: y contains previously unseen labels: [3]

In [15]:
cleaned_titanic_df.to_csv("final_titanic_data.csv", index = True)

In [9]:
cleaned_titanic_df

PassengerId  Survived     Sex  Parch Cabin Embarked
0            1.0       0.0    male    0.0   NaN        S
1            2.0       1.0  female    0.0   C85        C
2            3.0       1.0  female    0.0   NaN        S
3            4.0       1.0  female    0.0  C123        S
4            5.0       0.0    male    0.0   NaN        S
..           ...       ...     ...    ...   ...      ...
884        887.0       0.0    male    0.0   NaN        S
885        888.0       1.0  female    0.0   B42        S
886        889.0       0.0  female    2.0   NaN        S
887        890.0       1.0    male    0.0  C148        C
888        891.0       0.0    male    0.0   NaN        Q

[889 rows x 6 columns]